import type { Config } from "tailwindcss";

const config: Config = {
  content: [
    "./pages/**/*.{js,ts,jsx,tsx,mdx}",
    "./components/**/*.{js,ts,jsx,tsx,mdx}",
    "./app/**/*.{js,ts,jsx,tsx,mdx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        background: "#0b1326",
        surface: "#0b1326",
        "surface-dim": "#0b1326",
        "surface-container-lowest": "#060e20",
        "surface-container-low": "#131b2e",
        "surface-container": "#171f33",
        "surface-container-high": "#222a3d",
        "surface-container-highest": "#2d3449",
        "surface-variant": "#2d3449",
        "surface-bright": "#31394d",
        "on-background": "#dae2fd",
        "on-surface": "#dae2fd",
        "on-surface-variant": "#bec8d2",
        "inverse-surface": "#dae2fd",
        "inverse-on-surface": "#283044",
        primary: "#89ceff",
        "on-primary": "#00344d",
        "primary-container": "#0ea5e9",
        "on-primary-container": "#003751",
        "primary-fixed": "#c9e6ff",
        "primary-fixed-dim": "#89ceff",
        "on-primary-fixed": "#001e2f",
        "on-primary-fixed-variant": "#004c6e",
        "inverse-primary": "#006591",
        "surface-tint": "#89ceff",
        secondary: "#4edea3",
        "on-secondary": "#003824",
        "secondary-container": "#00a572",
        "on-secondary-container": "#00311f",
        "secondary-fixed": "#6ffbbe",
        "secondary-fixed-dim": "#4edea3",
        "on-secondary-fixed": "#002113",
        "on-secondary-fixed-variant": "#005236",
        tertiary: "#ffb95f",
        "on-tertiary": "#472a00",
        "tertiary-container": "#d88a00",
        "on-tertiary-container": "#4a2c00",
        "tertiary-fixed": "#ffddb8",
        "tertiary-fixed-dim": "#ffb95f",
        "on-tertiary-fixed": "#2a1700",
        "on-tertiary-fixed-variant": "#653e00",
        error: "#ffb4ab",
        "on-error": "#690005",
        "error-container": "#93000a",
        "on-error-container": "#ffdad6",
        outline: "#88929b",
        "outline-variant": "#3e4850",
      },
      borderRadius: {
        DEFAULT: "0.25rem",
        sm: "0.125rem",
        md: "0.375rem",
        lg: "0.5rem",
        xl: "0.75rem",
        "2xl": "1rem",
        "3xl": "1.5rem",
        full: "9999px",
      },
      fontFamily: {
        headline: ["var(--font-space-grotesk)", "Space Grotesk", "sans-serif"],
        body: ["var(--font-inter)", "Inter", "sans-serif"],
        label: ["var(--font-inter)", "Inter", "sans-serif"],
      },
      keyframes: {
        "kinetic-ring": {
          "0%, 100%": { opacity: "0.2" },
          "50%": { opacity: "0.5" },
        },
        "action-flash": {
          "0%": { backgroundColor: "rgba(78, 222, 163, 0.25)" },
          "100%": { backgroundColor: "rgba(78, 222, 163, 0)" },
        },
        "tooltip-appear": {
          "0%": { opacity: "0", transform: "translateY(10px)" },
          "100%": { opacity: "1", transform: "translateY(0)" },
        },
        "ar-pulse": {
          "0%, 100%": { opacity: "0.04", transform: "scale(1)" },
          "50%": { opacity: "0.08", transform: "scale(1.06)" },
        },
      },
      animation: {
        "kinetic-ring": "kinetic-ring 2s ease-in-out infinite",
        "action-flash": "action-flash 600ms ease-out forwards",
        "tooltip-appear": "tooltip-appear 300ms ease-out forwards",
        "ar-pulse": "ar-pulse 3s ease-in-out infinite",
      },
    },
  },
  plugins: [],
};

export default config;
